# Generated by Django 5.0 on 2024-01-18 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_master', '0010_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('joindate', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('salary', models.PositiveIntegerField()),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode/')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')])),
                ('status', models.BooleanField(default=True)),
                ('desigid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.designation')),
                ('dptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.department')),
                ('empcatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.employee_category')),
                ('qualifid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='empdesig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('desigid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.designation')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.adminemp')),
            ],
        ),
        migrations.CreateModel(
            name='empdpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('dptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.department')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.adminemp')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='admin_employee.adminemp')),
            ],
        ),
        migrations.CreateModel(
            name='scd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.class')),
                ('divid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.division')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.adminemp')),
                ('subid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.subject')),
            ],
        ),
    ]
